### ISSUE TITLE
执行sh quickstart.sh启动项目报错

### ISSUE THREAD

**Issue by Micheal-yang-china** [vipshop/pallas#149]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.pallas.demo.LaunchAll.main(LaunchAll.java:66)
Caused by: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch. Check previous logs for details
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
        at com.vip.pallas.demo.Launcher.launchES(LaunchAll.java:174)
        at com.vip.pallas.demo.Launcher.main(LaunchAll.java:93)
        ... 5 more
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch. Check previous logs for details
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
        at com.vip.pallas.demo.Launcher.lambda$launchES$1(LaunchAll.java:154)
        at java.lang.Thread.run(Thread.java:748)
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch. Check previous logs for details
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
        at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
        at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
        at com.vip.pallas.demo.Launcher.lambda$launchES$0(LaunchAll.java:133)
        at java.lang.Thread.run(Thread.java:748)
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Stopping elasticsearch server...
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Stopping elasticsearch server...
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Stopping elasticsearch server...
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Elasticsearch exited with RC 1
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Elasticsearch exited with RC 1
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Elasticsearch exited with RC 1
[2020-03-31 17:16:40.938] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Removing installation directory...
[2020-03-31 17:16:40.939] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Removing installation directory...
[2020-03-31 17:16:40.939] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Removing installation directory...
[2020-03-31 17:16:40.951] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Finishing...
[2020-03-31 17:16:40.951] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Finishing...
[2020-03-31 17:16:40.951] [INFO] [ElsInstanceCleaner] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> Finishing...

**Comment by NathanChan** [comment]
运行脚本的机器配置是否比较低？看报错栈是内嵌的ES启动超时了

**Comment by Micheal-yang-china** [comment]
4c 4g够不够？最低要求是多少呀？

**Comment by NathanChan** [comment]
内存估计不够，试升到8g看看，demo为搭建完整pallas环境，启动了3个ES节点(每个堆大小256m)、一个jetty实例、一个pallas console和一个pallas search。4g应该不够用

**Comment by Micheal-yang-china** [comment]
我把内存加到了10g，依然报同样的错
