### ISSUE TITLE
pallas 部署8081 端口起不来

### ISSUE THREAD

**Issue by lisw1993** [vipshop/pallas#15]
执行quickstart.sh 后3个es节点9200，9210，9220 是存活的
但是web控制台却拉不起来

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vip.pallas.demo.LaunchAll.main(LaunchAll.java:66)
Caused by: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.launchES(LaunchAll.java:174)
	at com.vip.pallas.demo.Launcher.main(LaunchAll.java:93)
	... 5 more
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.lambda$launchES$1(LaunchAll.java:154)
	at java.lang.Thread.run(Thread.java:748)
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.lambda$launchES$0(LaunchAll.java:133)
	at java.lang.Thread.run(Thread.java:748)

**Comment by TannerCai** [comment]
WEB控制台没有拉起是因为在ES的启动过程就出现了异常，导致程序终止。鉴于9200，9210，9220端口存活。可能是之前的某一次启动未进行正常的关闭，导致ES进程未被正常的关闭导致。可以尝试kill 相关的进程进行重启。

**Comment by lisw1993** [comment]
es 节点是在执行.sh 过后启动的
9300 9310 9320 
9200 9210 9220
都是正常启动的

[2019-02-02 17:21:29.799] [INFO] [EmbeddedElsHandler] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> [2019-02-02T17:21:29,798][INFO ][o.e.n.Node               ] [w5cgKMh] started

**Comment by TannerCai** [comment]
ES成功启动的话，可以看到“ElasticSearch started...”，可以仔细关注下9220  9320端口的这个节点，以及是否有info输出“start es successfully.”

**Comment by lisw1993** [comment]
[2019-02-12 14:27:53.712] [INFO] [EmbeddedElsHandler] [p.allegro.tech.embeddedelasticsearch.ElasticServer] >>> [2019-02-12T14:27:53,712][INFO ][o.e.p.PluginsService     ] [seZIW1C] no plugins loaded
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.lambda$launchES$0(LaunchAll.java:133)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vip.pallas.demo.LaunchAll.main(LaunchAll.java:66)
Caused by: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.launchES(LaunchAll.java:174)
	at com.vip.pallas.demo.Launcher.main(LaunchAll.java:93)
	... 5 more
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:124)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:79)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:60)
	at com.vip.pallas.demo.Launcher.lambda$launchES$1(LaunchAll.java:154)
	at java.lang.Thread.run(Thread.java:748)


有time-out 异常这个该如何解决

**Comment by owenericsson** [comment]
服务支持麻烦可以到开源微信群讨论吧，那样可以得到更加迅速的问题交流
