### ISSUE TITLE
运行quickstart.sh报错“Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.”

### ISSUE THREAD

**Issue by Jensen-Lone** [vipshop/pallas#150]
机器配置8核16G内存。centos7.5系统。使用MobaXterm工具远程登陆。
使用root用户执行“sh quickstart.sh”失败报错“can not run elasticsearch as root”。于是新增用户“pallas”，且为目录“/app/logs”添加权限'+ R'后，执行“sh quickstart.sh”，报错如下：
（求解，求指教，甚急）

21:00:54,439 |-INFO in ch.qos.logback.classic.LoggerContext[pallas-demo] - Could NOT find resource [logback.groovy]
21:00:54,439 |-INFO in ch.qos.logback.classic.LoggerContext[pallas-demo] - Could NOT find resource [logback-test.xml]
21:00:54,439 |-INFO in ch.qos.logback.classic.LoggerContext[pallas-demo] - Found resource [logback.xml] at [jar:file:/home/quickstart/pallas-demo.jar!/logback.xml]
21:00:54,440 |-WARN in ch.qos.logback.classic.LoggerContext[pallas-demo] - Resource [logback.xml] occurs multiple times on the classpath.
21:00:54,440 |-WARN in ch.qos.logback.classic.LoggerContext[pallas-demo] - Resource [logback.xml] occurs at [jar:file:/home/quickstart/lib/pallas-search-master-SNAPSHOT.jar!/logback.xml]
21:00:54,440 |-WARN in ch.qos.logback.classic.LoggerContext[pallas-demo] - Resource [logback.xml] occurs at [jar:file:/home/quickstart/pallas-demo.jar!/logback.xml]
21:00:54,440 |-WARN in ch.qos.logback.classic.LoggerContext[pallas-demo] - Resource [logback.xml] occurs at [jar:file:/home/quickstart/lib/pallas-console-master-SNAPSHOT.jar!/logback.xml]
21:00:54,454 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@192d3247 - URL [jar:file:/home/quickstart/pallas-demo.jar!/logback.xml] is not of type file
21:00:54,505 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
21:01:24,559 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [pallas-demo]
21:01:24,559 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
21:01:24,561 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
21:01:24,567 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:01:24,615 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:01:24,617 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
21:01:24,623 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@3ecd23d9 - No compression will be used
21:01:24,627 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:01:24,628 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /apps/logs/log_receiver/pallas-demo/pallas-demo-log.log
21:01:24,628 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/apps/logs/log_receiver/pallas-demo/pallas-demo-log.log]
21:01:24,629 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
21:01:24,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_FILE]
21:01:24,631 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNC_FILE]
21:01:24,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_FILE] - Attaching appender named [FILE] to AsyncAppender.
21:01:24,632 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_FILE] - Setting discardingThreshold to 0
21:01:24,632 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:01:24,632 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [AUDITLOG-APPENDER]
21:01:24,633 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@569cfc36 - No compression will be used
21:01:24,634 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:01:24,634 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[AUDITLOG-APPENDER] - Active log file name: /apps/logs/log_receiver/pallas-demo/pallas-demo-audit.log
21:01:24,634 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[AUDITLOG-APPENDER] - File property is set to [/apps/logs/log_receiver/pallas-demo/pallas-demo-audit.log]
21:01:24,635 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:01:24,635 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR]
21:01:24,637 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@43bd930a - No compression will be used
21:01:24,637 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:01:24,638 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - Active log file name: /apps/logs/log_receiver/pallas-demo/pallas-demo-error.log
21:01:24,638 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - File property is set to [/apps/logs/log_receiver/pallas-demo/pallas-demo-error.log]
21:01:24,638 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [AUDITLOG] to INFO
21:01:24,638 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [AUDITLOG] to true
21:01:24,638 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [AUDITLOG-APPENDER] to Logger[AUDITLOG]
21:01:24,639 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.vip.pallas] to false
21:01:24,820 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - com.vip.pallas level set to INFO
21:01:24,822 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.vip.pallas]
21:01:24,823 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_FILE] to Logger[com.vip.pallas]
21:01:24,823 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to Logger[com.vip.pallas]
21:01:24,823 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
21:01:24,825 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
21:01:24,825 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_FILE] to Logger[ROOT]
21:01:24,825 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to Logger[ROOT]
21:01:24,825 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
21:01:24,826 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@33723e30 - Registering current configuration as safe fallback point

MobaXterm X11 proxy: Unsupported authorisation protocol
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at java.awt.Desktop.isDesktopSupported(Desktop.java:169)
        at java.awt.Desktop.getDesktop(Desktop.java:143)
        at com.vip.pallas.demo.Launcher.<clinit>(LaunchAll.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.pallas.demo.LaunchAll.main(LaunchAll.java:66)

**Comment by GDUFZXP** [comment]
这个解决了吗？我也遇到了。。。。windows启动开箱即用

**Comment by Jensen-Lone** [comment]
收到，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vipshop/pallas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上9:12
收件人:&nbsp;"vipshop/pallas"<pallas@noreply.github.com&gt;;
抄送:&nbsp;"Jansen Lone"<369236981@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vipshop/pallas] 运行quickstart.sh报错“Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.” (#150)





 
这个解决了吗？我也遇到了。。。。windows启动开箱即用
